### ISSUE TITLE
ECDSA Signature instead of String

### ISSUE THREAD

**Issue by hartmannj** [bakkenbaeck/EtherealCereal#5]
When signing a value with etherealCereal.sign(message: value), how do I get the signature values (v, r, s) instead of a String?

**Comment by Elland** [comment]
We don't really expose it directly at the moment. The idea for now is to keep it as high level as possible. You can look into the C code that does expose it, and if you want to extend EtherealCereal to expose it as well, I'd happily merge it. 👍

**Comment by Elland** [comment]
By the way, IIRC:
v is https://github.com/bakkenbaeck/EtherealCereal/blob/master/EtherealCereal/EtherWrapper.m#L47

r and s can be extracted from https://github.com/bakkenbaeck/EtherealCereal/blob/master/EtherealCereal/EtherWrapper.m#L53

**Comment by hartmannj** [comment]
Thanks for the tip!
Actually, by looking at the String result, the signature values can be parsed out of it.
